### ISSUE TITLE
Problem with importing face_detection.build_detector

### ISSUE THREAD

**Issue by Zeleni9** [hukkelas/DSFD-Pytorch-Inference#13]
Hi, 

after pip installation of your module I have a problem with importing face_detection and build detector. The error is: 
```
detector = face_detection.build_detector("RetinaNetResNet50", confidence_threshold=.5, nms_iou_threshold=.3)
AttributeError: module 'face_detection' has no attribute 'build_detector'
```

The call is written 

```
import face_detection
detector = face_detection.build_detector("RetinaNetResNet50", confidence_threshold=.5, nms_iou_threshold=.3)
```

Thanks.

**Comment by hukkelas** [comment]
Hi. Did you install with:
```
pip install git+https://github.com/hukkelas/DSFD-Pytorch-Inference.git
```
If not. Please uninstall and reinstall the package with this.

**Comment by Zeleni9** [comment]
Yeah I did it with git link, but still the error persist, which is weird since it should work. I will try to download repo and test it out.

**Comment by chikiuso** [comment]
Hi @Zeleni9 , I face the same problem and walkthrough all steps above but no luck, how do you solve it? thanks.
