### ISSUE TITLE
TRT inference error

### ISSUE THREAD

**Issue by rnekk2** [hukkelas/DSFD-Pytorch-Inference#15]
[TensorRT] ERROR: INVALID_ARGUMENT: Cannot deserialize with an empty memory buffer.
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "test_video.py", line 33, in <module>
    detector = TensorRTRetinaFace(input_imshape,inference_imshape)
  File "/data/DSFD-Pytorch-Inference/face_detection/retinaface/tensorrt_wrap.py", line 38, in __init__
    self.context = self.engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'

Seeing issues running inference using tensorrt. How to fix it.

Tensorrt version 7.1.3
Torch version - 1.4.0

**Comment by hukkelas** [comment]
Hi, you were not able to build an engine.

Sadly, I do not have the capacity to help you debug this issue with tensorRT, as this is not something I'm not that experienced with.
If you are not familiar with TensorRT, I recommend you to use the default pytorch version.
