### ISSUE TITLE
Error while doing inference on video 

### ISSUE THREAD

**Issue by Math2code** [hukkelas/DSFD-Pytorch-Inference#2]
Hi all,

I encounter the following error while doing inference on video and it is likely to happen when I down-scale the frame. Do you know how should I fixed it ?
~\DSFD-Pytorch-Inference\dsfd\detect.py in detect_face(self, image, confidence_threshold, shrink)
     41 
     42         with torch.no_grad():
---> 43             y = self.net(x, confidence_threshold, self.nms_iou_threshold)
     44 
     45         detections = y.data.cpu().numpy()

~\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

\DSFD-Pytorch-Inference\dsfd\face_ssd.py in forward(self, x, confidence_threshold, nms_threshold)
    191             self.priors,
    192             confidence_threshold,
--> 193             nms_threshold
    194         )
    195         return output

~\DSFD-Pytorch-Inference\dsfd\utils.py in forward(self, loc_data, conf_data, prior_data, confidence_threshold, nms_threshold)
     65             if conf_scores.dim() == 0:
     66                 final_ouput.append(torch.empty(0, 5))
---> 67             keep_idx = nms(decoded_boxes, conf_scores, nms_threshold)
     68 
     69             scores = conf_scores[keep_idx].view(1, -1, 1)

~\Anaconda3\envs\py36\lib\site-packages\torchvision\ops\boxes.py in nms(boxes, scores, iou_threshold)
     31     """
     32     _C = _lazy_import()
---> 33     return _C.nms(boxes, scores, iou_threshold)
     34 
     35 

RuntimeError: too many indices for tensor of dimension 0 (got 1) (index at ..\aten\src\ATen\native\Indexing.cpp:235)
(no backtrace available)

**Comment by Math2code** [comment]
I had an add-hoc solution as follow:
--- a/dsfd/utils.py                                                                                                                                +++ b/dsfd/utils.py                                                                                                                                @@ -60,10 +60,15 @@ class Detect:                                                                                                                               # Very costly operation, conf_score shape: [172845]                                                                                                indices = (conf_scores >= confidence_threshold).nonzero().squeeze()                                                                                                                                                                                                                                   decoded_boxes = decoded_boxes[indices]                                                                                                -                                                                                                                                                               conf_scores = conf_scores[indices]                                                                                                    +                                                                                                                                                  +            if decoded_boxes.dim() == 1:                                                                                                          +                decoded_boxes =  torch.empty(0,4).cuda()                                                                                          +                conf_scores = torch.empty(0, 5).cuda()                                                                                            +                                                                                                                                                               if conf_scores.dim() == 0:                                                                                                                             final_ouput.append(torch.empty(0, 5))                                                                                             +                                                                                                                                                               keep_idx = nms(decoded_boxes, conf_scores, nms_threshold)                                                                                                                                                                                                                                             scores = conf_scores[keep_idx].view(1, -1, 1)

**Comment by hukkelas** [comment]
Hey, thanks for noticing this bug. 
I've experienced this with the DeepPrivacy github, but forgot to submit a bug fix in this repo. [This commit](https://github.com/hukkelas/DSFD-Pytorch-Inference/commit/834ba8d2a08ca3c90f25050c774e0bd6df09370e) should fix the issue :) 

The issue is that when there is no bounding box predictions with  a higher confidence than the threshold, the NMS code spits out that error.
