### ISSUE TITLE
Broken DSFD checkpoint URL

### ISSUE THREAD

**Issue by rohanrao619** [hukkelas/DSFD-Pytorch-Inference#20]
@hukkelas Looks like the URL of the DSFD checkpoint is not working. Getting HTTP Error 308: Permanent Redirect when I run this:
detector = face_detection.build_detector("DSFDDetector", confidence_threshold=.5, nms_iou_threshold=.3)

However "RetinaNetResNet50"  and "RetinaNetMobileNetV1" are working fine.
Please check this issue and fix it. Thanks!

**Comment by hukkelas** [comment]
Fixed now!

**Comment by NikethanPoojary** [comment]
I'm experiencing the same issue. Please resolve this DSFD issue as @rohanrao619 mentioned

**Comment by hukkelas** [comment]
This should be fixed in master. Please ensure that you get the latest version:
```
 pip install --upgrade git+https://github.com/hukkelas/DSFD-Pytorch-Inference.git
```
