### ISSUE TITLE
Receiving HTTP 308 error while creating detector

### ISSUE THREAD

**Issue by Prajwal-P** [hukkelas/DSFD-Pytorch-Inference#21]
Hi, I'm trying to create a detector using the same code as mentioned in readme. I'm trying to do this in google colab but I'm receiving a HTTP 308 and not able to find out why is that. Can any one help me with this please?

My code:
```
import face_detection
print(face_detection.available_detectors) # This is working fine
detector = face_detection.build_detector("DSFDDetector", confidence_threshold=.5, nms_iou_threshold=.3) # throws HTTP 308 error
```

Screenshot of error I'm getting:
![image](https://user-images.githubusercontent.com/50076923/117580457-a116fd00-b115-11eb-99f2-3078227f5e1c.png)

**Comment by hukkelas** [comment]
This is fixed in master. Try to reinstall with:
```pip install git+https://github.com/hukkelas/DSFD-Pytorch-Inference.git```

**Comment by Prajwal-P** [comment]
Sorry, It didn't work. Still getting the same error
