### ISSUE TITLE
Run on CPU

### ISSUE THREAD

**Issue by datasetsk** [hukkelas/DSFD-Pytorch-Inference#22]
By default, the code is running on GPU and causing this error `RuntimeError: CUDA out of memory. Tried to allocate 90.00 MiB (GPU 0; 2.00 GiB total capacity; 941.01 MiB already allocated; 43.44 MiB free; 1.14 GiB reserved in total by PyTorch)`. Is it possible to change it to run on CPU

**Comment by hukkelas** [comment]
When you call the script use `CUDA_VISIBLE_DEVICES="" python ....` and the GPU will not be visible to pytorch.

**Comment by datasetsk** [comment]
thanks a lot
