### ISSUE TITLE
Returning the face landmarks?

### ISSUE THREAD

**Issue by rizwanishaq** [hukkelas/DSFD-Pytorch-Inference#23]
how we can return the face-landmark from the detect method?

**Comment by hukkelas** [comment]
You can call [`batched_detect_with_landmarks`](https://github.com/hukkelas/DSFD-Pytorch-Inference/blob/7bbe1f61ef5cb951a6e55e0a80e4972419edf5ca/face_detection/retinaface/detect.py#L48).

Example code:
```python
import cv2
import face_detection
print(face_detection.available_detectors)
detector = face_detection.build_detector(
  "RetinaNetResNet50", confidence_threshold=.5, nms_iou_threshold=.3)
# BGR to RGB
im = cv2.imread("path_to_im.jpg")[:, :, ::-1]

boxes, landmarks = detector. batched_detect_with_landmarks(im)
```

See function description to see how the landmarks/boxes are returned.

**Comment by sainivedh** [comment]
Make sure to add axis for batched inference

im = im[np.newaxis, ...]
