### ISSUE TITLE
Inference Speed Results

### ISSUE THREAD

**Issue by leg0m4n** [hukkelas/DSFD-Pytorch-Inference#26]
Hi, thank you so much for the code!

I was testing RetinaMobileNetV1 and timing it with torch. For some reason on my rtx3090 it took 472ms to do inference on  1438x892x3 image. Seems too slow, compared to your results. My code is below. Do you have any idea why it may be happening?
<img width="1112" alt="Screen Shot 2021-12-26 at 3 39 02 PM" src="https://user-images.githubusercontent.com/40952269/147419517-741ca626-797c-46df-a5b6-44313e3891e9.png">

**Comment by hukkelas** [comment]
You are measuring inference over a single forward pass and your timing includes model setup time.
My inference benchmark is the average over 1000 forward passes. Please instead test with the [benchmark.py](https://github.com/hukkelas/DSFD-Pytorch-Inference/blob/master/benchmark.py) script.

**Comment by leg0m4n** [comment]
My bad, thank you!
