### ISSUE TITLE
Zeros in confidence score

### ISSUE THREAD

**Issue by juracyemanuel** [hukkelas/DSFD-Pytorch-Inference#28]
Hi,
I am always getting zeros as confidence values, as consequence I am not able to plot the Precision vs Recall curve.
5
829 270 920 374 0
565 346 582 372 0
493 342 514 371 0
677 353 687 367 0
457 352 466 362 0
Could you give me a hint about what could be happened ?

**Comment by hukkelas** [comment]
Could you give a minimal script to reproduce your results? That would help me debug your issue :) 

Sorry for the late answer, been off on vacation
