### ISSUE TITLE
Batch inference

### ISSUE THREAD

**Issue by nosound2** [hukkelas/DSFD-Pytorch-Inference#3]
Thank you for the great code!

Is batch prediction possible (many images at once), any plans to add it? Do you think we can expect a speed up?

Thanks,
Zahar

**Comment by hukkelas** [comment]
Thanks!
Currently, this is not supported as we do not set a fixed width for the input image.

If you have a fixed input image size, this should definitely give you a speed up. But it's a case-by-case basis.

I might look into this at a later time, but can't promise anything :)

**Comment by hukkelas** [comment]
Hey,
Not sure if it's still relevant for you, but I've added support for semi-batched inference.
neural network is run in batched fashion, but non-maxima suppression / confidence score thresholding is still done per-image basis.

But it's all abstracted away, see:
https://github.com/hukkelas/DSFD-Pytorch-Inference#batched-inference
