### ISSUE TITLE
Install with Pip not working anymore

### ISSUE THREAD

**Issue by johko** [hukkelas/DSFD-Pytorch-Inference#30]
Hi,
since your latest commit and the removal of torch from the setup.py I get an error message when trying to run `pip install git+https://github.com/hukkelas/DSFD-Pytorch-Inference.git` which says that it cannot find torch:
`ModuleNotFoundError: No module named 'torch'`

What is the intention behind removing it from the setup.py?

**Comment by hukkelas** [comment]
Having torch in the requirements would trigger reinstall of torch for some environments, often installing cpu binaries even though cuda environment is available.

Check out the pytorch website for installating pytorch: https://pytorch.org/get-started/locally/
