### ISSUE TITLE
Can not get checkpoint parameters file.

### ISSUE THREAD

**Issue by jackyfaster** [hukkelas/DSFD-Pytorch-Inference#8]
Hi, 
    I installed the great tool with 'pip install face_detection' ,but there is no parameters file in '.cache\torch\checkpoints'.  I do not know why.  Could you give me some helpful suggestions that what i should do,
            best regards!

**Comment by elysoly** [comment]
Hi,
you can download them from the links below: 
 "https://folk.ntnu.no/haakohu/RetinaFace_mobilenet025.pth"
"http://folk.ntnu.no/haakohu/WIDERFace_DSFD_RES152.pth"
 "https://github.com/hukkelas/DSFD-Pytorch-Inference.git"

**Comment by jackyfaster** [comment]
It's great ,thanks a lot !
